version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: insecure
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  vault:
    build:
      context: build/docker/vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - "vaultlogs:/vault/logs"
      - "vaultfile:/vault/file"
    depends_on:
      - db
    command: server
  web:
    build:
      context: build/docker/web
    ports:
      - "8080:8080"
    depends_on:
      - vault
      - db
    environment:
      - VAULT_TOKEN

volumes:
  vaultlogs:
  vaultfile:
  pgdata:
